### ISSUE TITLE
rake aborted

### ISSUE THREAD

**Issue by Motinaga** [OmertaBeyond/omerta_logger#171]
on rake:seed i get:

rake aborted!
Your version of SQLite (3.7.17) is too old. Active Record supports SQLite >= 3.8.

can you help me?

**Comment by Baelor** [comment]
@Motinaga what OS/version are you running this on? The error indicates that the version of sqlite on your system is too old. You'll need to get a more recent version, details would depend on your OS - you may find a more recent version in your package manager/a third party repo, or maybe you'll need to build your own.

Generally, an up-to-date version of Debian or Ubuntu should work.
